version: '2.2'
services:
  users-service:
    build: .
    container_name: service
    ports:
     - "10000:80"
    links:
      - db:db
    depends_on:
     - db
    cpus: 1
    environment:
     - DATABASE_HOST=db

  db:
    build: ./test-db
    mem_limit: 500m
    ports:
      - "3306:3306"
